config/routes.rb
Rails.application.routes.draw do

 namespace :admin do
    get '/' => 'base#index'

    resources :books

    get '/add' => 'administrators#new'
    post '/add' => 'administrators#create'

    get '/login' => 'sessions#new'
    post '/login' => 'sessions#create'
    delete '/logout' => 'sessions#destroy'

    get '/booksprice' => 'books#price'
    get '/bookstitle' => 'books#title'
  end
end

app/models/administrator.rb
class Administrator < ActiveRecord::Base
  has_secure_password

  validates :username, presence: true, uniqueness: true
end

app/models/book.rb
class Book < ActiveRecord::Base
end

app/controllers/admin/administrators_controller.rb
class Admin::AdministratorsController < ApplicationController
  layout 'admin'

  def new
    @administrator = Administrator.new
  end

  def create
    @administrator = Administrator.new(administrator_params)
    if @administrator.save
      session[:administrator_id] = @administrator.id
      redirect_to admin_books_path
    else
      render :new
    end
  end

    private

    def administrator_params
      params.require(:administrator).permit(:username, :password, :password_confirmation)
    end
  end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  layout 'admin'

  def index
  end
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < ApplicationController
    layout 'admin'
    before_action :find_book, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_administrator

    def index
      if params[:order_by]
        @books = Book.all.order(params[:order_by].to_sym)
      else
        @books = Book.all
      end
    end

    def new
      @book = Book.new
    end

    def create
      @book = Book.new(book_params)
      if @book.save
        redirect_to admin_books_path
      else
        render :new
      end
    end

    def edit
    end

    def update
      if @book.update(book_params)
        redirect_to admin_books_path
      else
        render :edit
      end
    end

    def show
    end

    def destroy
      @book.destroy
      redirect_to admin_books_path
    end

    private

    def find_book
      @book = Book.find(params[:id])
    end

    def book_params
      params.require(:book).permit(:title, :author, :pages, :price, :in_stock)
    end

end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < ApplicationController
  layout 'admin'
  def new

  end

  def create
    @administrator = Administrator.where(username: params[:username]).first
    if @administrator.present? && @administrator.authenticate(params[:password])
      session[:administrator_id] = @administrator.id
      flash[:success] = "Administrator successfully signed in!"
      redirect_to admin_books_path
    else
      flash[:danger] = "You aint no administrator friend..."
      render :new
    end
  end

    def destroy
      session[:administrator_id] = nil
      redirect_to admin_login_path
    end
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_administrator
    @current_administrator ||= Administrator.where(id: session[:administrator_id]).first
  end

  helper_method :current_administrator

  private

  def authenticate_administrator
    unless session[:administrator_id].present? && current_administrator.present?
      flash[:alert] = 'Must be an administrator to access this page'
      redirect_to admin_login_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def administrator_signed_in?
    current_administrator.present?
  end
  def danger_none_left(stock)
    if stock <= 0
      return "danger"
    end
  end
end

app/views/admin/administrators/new.html.erb
Dont even try

app/views/admin/books/edit.html.erb
<h1> Manage Bookstore </h1>
<h2> Edit Book </h2>
<%=  form_for(@book, url: admin_book_path)  do |f| %>
<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Page Count</th>
      <th>Price</th>
      <th>In Stock</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tr>
    <td><%= f.text_field (:title) %></td>
    <td><%= f.text_field (:author) %></td>
    <td><%= f.text_field (:pages) %></td>
    <td><%= f.text_field (:price) %></td>
    <td><%= f.text_field (:in_stock) %></td>
    <td>
    <%= f.submit('Update') %>
    </td>
  </tr>
</table>
<% end %>

app/views/admin/books/index.html.erb
<h1> Manage Bookstore </h1>
<%= link_to("Add Book", new_admin_book_path) %>
<br>
<br>
Sort By: <%= link_to 'Title', admin_books_path({order_by: 'title'})  %>,
          <%= link_to 'Price', admin_books_path({order_by: 'price'}) %>,
          <%= link_to 'Author', admin_books_path({order_by: 'author'}) %>
<br>
<br>
<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Page Count</th>
      <th>Price</th>
      <th>In Stock</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <% @books.each do |book| %>
  <tr class="<%= danger_none_left(book.in_stock) %>">
    <td><%= book.title %></td>
    <td><%= book.author %></td>
    <td><%= book.pages %></td>
    <td><%= book.price %></td>
    <td><%= book.in_stock %></td>
    <td>
    <%= link_to("Edit", edit_admin_book_path(book.id)) %>
    <%= link_to("Delete", admin_book_path(book.id), method: :delete) %>
    </td>
  </tr>
  <% end %>
</table>

app/views/admin/books/new.html.erb
<h1> Manage Bookstore </h1>
<h2> New Book </h2>
<%=  form_for(@book, url: admin_books_path)  do |f| %>
<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Page Count</th>
      <th>Price</th>
      <th>In Stock</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tr>
    <td><%= f.text_field (:title) %></td>
    <td><%= f.text_field (:author) %></td>
    <td><%= f.text_field (:pages) %></td>
    <td><%= f.text_field (:price) %></td>
    <td><%= f.text_field (:in_stock) %></td>
    <td>
    <%= f.submit('Update') %>
    </td>
  </tr>
</table>
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookstore</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <% if administrator_signed_in? %>
          <%= link_to 'Logout', admin_logout_path, method: :delete %>
        <% else %>
          <%= link_to 'Login', admin_login_path%>
        <% end %>
        <% flash.each do |key, value| %>
          <div class="alert alert-<%= key %>"><%= value %></div>
        <% end %>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-12">
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookstore</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>